### ISSUE TITLE
How big is this thing?

### ISSUE THREAD

**Issue by linuxbastard** [geddski/overwatch-hero-picker#1]
Hi,

Wanted to test it out but was already at 90MB and it was still downloading. How big is the whole repo?

Thanks for any clarification.

**Comment by linuxbastard** [comment]
Yeah, I just found the culprit. There's a video that's about 86MB?

And I guess the images are high res as well? WIll just keep git clone running then.

**Comment by geddski** [comment]
@linuxbastard haha yep sorry about that! I'll probably use a shorter video next time :)
